//
// ForecastAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ForecastAPI {

    /**
     Current weather for coordinates
     
     - parameter latitude: (query)  
     - parameter longitude: (query)  
     - parameter currentWeather: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OpenMeteoForecastResponse
     */
    open class func getCurrentWeatherForecast(latitude: Double, longitude: Double, currentWeather: Bool, apiConfiguration: OpenMeteoAPIConfiguration = OpenMeteoAPIConfiguration.shared) async throws(ErrorResponse) -> OpenMeteoForecastResponse {
        return try await getCurrentWeatherForecastWithRequestBuilder(latitude: latitude, longitude: longitude, currentWeather: currentWeather, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Current weather for coordinates
     - GET /forecast
     - parameter latitude: (query)  
     - parameter longitude: (query)  
     - parameter currentWeather: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OpenMeteoForecastResponse> 
     */
    open class func getCurrentWeatherForecastWithRequestBuilder(latitude: Double, longitude: Double, currentWeather: Bool, apiConfiguration: OpenMeteoAPIConfiguration = OpenMeteoAPIConfiguration.shared) -> RequestBuilder<OpenMeteoForecastResponse> {
        let localVariablePath = "/forecast"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "latitude": (wrappedValue: latitude.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "longitude": (wrappedValue: longitude.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "current_weather": (wrappedValue: currentWeather.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OpenMeteoForecastResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
