//
// OpenMeteoForecastResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OpenMeteoForecastResponse: Sendable, Codable, Hashable {

    public private(set) var currentWeather: OpenMeteoCurrentWeather

    public init(currentWeather: OpenMeteoCurrentWeather) {
        self.currentWeather = currentWeather
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentWeather = "current_weather"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currentWeather, forKey: .currentWeather)
    }
}

