//
// OpenMeteoCurrentWeather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OpenMeteoCurrentWeather: Sendable, Codable, Hashable {

    public private(set) var temperature: Double
    public private(set) var windspeed: Double
    public private(set) var weathercode: Int
    public private(set) var time: String

    public init(temperature: Double, windspeed: Double, weathercode: Int, time: String) {
        self.temperature = temperature
        self.windspeed = windspeed
        self.weathercode = weathercode
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temperature
        case windspeed
        case weathercode
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(temperature, forKey: .temperature)
        try container.encode(windspeed, forKey: .windspeed)
        try container.encode(weathercode, forKey: .weathercode)
        try container.encode(time, forKey: .time)
    }
}

