//
// CityBikeLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeLocation: Sendable, Codable, Hashable {

    public private(set) var city: String?
    public private(set) var country: String?
    public private(set) var latitude: Double?
    public private(set) var longitude: Double?

    public init(city: String? = nil, country: String? = nil, latitude: Double? = nil, longitude: Double? = nil) {
        self.city = city
        self.country = country
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case city
        case country
        case latitude
        case longitude
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
    }
}

