//
// CityBikeStationExtra.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeStationExtra: Sendable, Codable, Hashable {

    public private(set) var slots: Int?
    public private(set) var address: String?
    /** 1 = open, 0 = closed */
    public private(set) var renting: Int?
    /** 1 = open, 0 = closed */
    public private(set) var returning: Int?
    public private(set) var ebikes: Int?
    public private(set) var hasEbikes: Bool?
    public private(set) var uid: String?
    public private(set) var rentalUris: CityBikeRentalURIs?

    public init(slots: Int? = nil, address: String? = nil, renting: Int? = nil, returning: Int? = nil, ebikes: Int? = nil, hasEbikes: Bool? = nil, uid: String? = nil, rentalUris: CityBikeRentalURIs? = nil) {
        self.slots = slots
        self.address = address
        self.renting = renting
        self.returning = returning
        self.ebikes = ebikes
        self.hasEbikes = hasEbikes
        self.uid = uid
        self.rentalUris = rentalUris
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slots
        case address
        case renting
        case returning
        case ebikes
        case hasEbikes = "has_ebikes"
        case uid
        case rentalUris = "rental_uris"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        slots = try container.decodeIfPresent(Int.self, forKey: .slots)
        address = try container.decodeIfPresent(String.self, forKey: .address)
        renting = Self.decodeFlexibleServiceFlag(from: container, forKey: .renting)
        returning = Self.decodeFlexibleServiceFlag(from: container, forKey: .returning)
        ebikes = try container.decodeIfPresent(Int.self, forKey: .ebikes)
        hasEbikes = try container.decodeIfPresent(Bool.self, forKey: .hasEbikes)
        uid = Self.decodeFlexibleUID(from: container)
        rentalUris = try container.decodeIfPresent(CityBikeRentalURIs.self, forKey: .rentalUris)
    }

    private static func decodeFlexibleUID(
        from container: KeyedDecodingContainer<CodingKeys>
    ) -> String? {
        if let string = try? container.decodeIfPresent(String.self, forKey: .uid) {
            return string
        }
        if let int = try? container.decodeIfPresent(Int.self, forKey: .uid) {
            return String(int)
        }
        return nil
    }

    /// CityBikes networks vary: `renting` / `returning` may be `0|1` (e.g. London) or `true|false` (e.g. Call-A-Bike Berlin).
    private static func decodeFlexibleServiceFlag(
        from container: KeyedDecodingContainer<CodingKeys>,
        forKey key: CodingKeys
    ) -> Int? {
        if let int = try? container.decodeIfPresent(Int.self, forKey: key) {
            return int
        }
        if let bool = try? container.decodeIfPresent(Bool.self, forKey: key) {
            return bool ? 1 : 0
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slots, forKey: .slots)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(renting, forKey: .renting)
        try container.encodeIfPresent(returning, forKey: .returning)
        try container.encodeIfPresent(ebikes, forKey: .ebikes)
        try container.encodeIfPresent(hasEbikes, forKey: .hasEbikes)
        try container.encodeIfPresent(uid, forKey: .uid)
        try container.encodeIfPresent(rentalUris, forKey: .rentalUris)
    }
}

