//
// CityBikeNetworkDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeNetworkDetail: Sendable, Codable, Hashable {

    public private(set) var id: String?
    public private(set) var name: String?
    public private(set) var stations: [CityBikeStation]?

    public init(id: String? = nil, name: String? = nil, stations: [CityBikeStation]? = nil) {
        self.id = id
        self.name = name
        self.stations = stations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case stations
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(String.self, forKey: .id)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        stations = try container.decodeIfPresent([CityBikeStation].self, forKey: .stations)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(stations, forKey: .stations)
    }
}


extension CityBikeNetworkDetail: Identifiable {}
