//
// CityBikeNetworksResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeNetworksResponse: Sendable, Codable, Hashable {

    public private(set) var networks: [CityBikeNetworkSummary]

    public init(networks: [CityBikeNetworkSummary]) {
        self.networks = networks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(networks, forKey: .networks)
    }
}

