//
// CityBikeStation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeStation: Sendable, Codable, Hashable {

    public private(set) var id: String
    public private(set) var name: String
    public private(set) var latitude: Double
    public private(set) var longitude: Double
    public private(set) var timestamp: String?
    public private(set) var freeBikes: Int?
    public private(set) var emptySlots: Int?
    public private(set) var extra: CityBikeStationExtra?

    public init(id: String, name: String, latitude: Double, longitude: Double, timestamp: String? = nil, freeBikes: Int? = nil, emptySlots: Int? = nil, extra: CityBikeStationExtra? = nil) {
        self.id = id
        self.name = name
        self.latitude = latitude
        self.longitude = longitude
        self.timestamp = timestamp
        self.freeBikes = freeBikes
        self.emptySlots = emptySlots
        self.extra = extra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case latitude
        case longitude
        case timestamp
        case freeBikes = "free_bikes"
        case emptySlots = "empty_slots"
        case extra
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        latitude = try container.decode(Double.self, forKey: .latitude)
        longitude = try container.decode(Double.self, forKey: .longitude)
        timestamp = try container.decodeIfPresent(String.self, forKey: .timestamp)
        freeBikes = try container.decodeIfPresent(Int.self, forKey: .freeBikes)
        emptySlots = try container.decodeIfPresent(Int.self, forKey: .emptySlots)
        extra = try container.decodeIfPresent(CityBikeStationExtra.self, forKey: .extra)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(latitude, forKey: .latitude)
        try container.encode(longitude, forKey: .longitude)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(freeBikes, forKey: .freeBikes)
        try container.encodeIfPresent(emptySlots, forKey: .emptySlots)
        try container.encodeIfPresent(extra, forKey: .extra)
    }
}


extension CityBikeStation: Identifiable {}
