//
// CityBikeNetworkSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeNetworkSummary: Sendable, Codable, Hashable {

    public private(set) var id: String
    public private(set) var name: String
    public private(set) var location: CityBikeLocation?

    public init(id: String, name: String, location: CityBikeLocation? = nil) {
        self.id = id
        self.name = name
        self.location = location
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case location
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(location, forKey: .location)
    }
}


extension CityBikeNetworkSummary: Identifiable {}
