//
// CityBikeRentalURIs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeRentalURIs: Sendable, Codable, Hashable {

    public private(set) var android: String?
    public private(set) var ios: String?

    public init(android: String? = nil, ios: String? = nil) {
        self.android = android
        self.ios = ios
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case android
        case ios
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(android, forKey: .android)
        try container.encodeIfPresent(ios, forKey: .ios)
    }
}

