//
// CityBikeNetworkDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityBikeNetworkDetailResponse: Sendable, Codable, Hashable {

    public private(set) var network: CityBikeNetworkDetail

    public init(network: CityBikeNetworkDetail) {
        self.network = network
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        network = try container.decode(CityBikeNetworkDetail.self, forKey: .network)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
    }
}

