//
// NetworksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class NetworksAPI {

    /**
     Network detail with stations
     
     - parameter networkId: (path)  
     - parameter fields: (query) Comma-separated fields; use &#x60;stations&#x60; for station list only. (optional, default to "stations")
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CityBikeNetworkDetailResponse
     */
    open class func getNetworkStations(networkId: String, fields: String? = nil, apiConfiguration: CityBikeAPIConfiguration = CityBikeAPIConfiguration.shared) async throws(ErrorResponse) -> CityBikeNetworkDetailResponse {
        return try await getNetworkStationsWithRequestBuilder(networkId: networkId, fields: fields, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Network detail with stations
     - GET /networks/{networkId}
     - parameter networkId: (path)  
     - parameter fields: (query) Comma-separated fields; use &#x60;stations&#x60; for station list only. (optional, default to "stations")
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CityBikeNetworkDetailResponse> 
     */
    open class func getNetworkStationsWithRequestBuilder(networkId: String, fields: String? = nil, apiConfiguration: CityBikeAPIConfiguration = CityBikeAPIConfiguration.shared) -> RequestBuilder<CityBikeNetworkDetailResponse> {
        var localVariablePath = "/networks/{networkId}"
        let networkIdPreEscape = "\(APIHelper.mapValueToPathItem(networkId))"
        let networkIdPostEscape = networkIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{networkId}", with: networkIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "fields": (wrappedValue: fields?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CityBikeNetworkDetailResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List all bike-share networks
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CityBikeNetworksResponse
     */
    open class func listNetworks(apiConfiguration: CityBikeAPIConfiguration = CityBikeAPIConfiguration.shared) async throws(ErrorResponse) -> CityBikeNetworksResponse {
        return try await listNetworksWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all bike-share networks
     - GET /networks
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CityBikeNetworksResponse> 
     */
    open class func listNetworksWithRequestBuilder(apiConfiguration: CityBikeAPIConfiguration = CityBikeAPIConfiguration.shared) -> RequestBuilder<CityBikeNetworksResponse> {
        let localVariablePath = "/networks"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CityBikeNetworksResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
